import { getAdapter } from "@/db";
import { generateUniqueCode } from "@/lib/uniqueCode";
import { renderQr } from "@/lib/qrGenerator";
import { saveQrImage, saveSvgFile } from "@/lib/imageProcessing";
import { ApiError } from "@/lib/errors";
import type { CreateQRInput, QRRecord, ScanLogEntry } from "@/types/qr";

const DEFAULTS = {
  dotShape: "square" as const,
  eyeOuterShape: "square" as const,
  eyeInnerShape: "square" as const,
  fgColor: "#000000",
  bgColor: "#FFFFFF",
  overallShape: "square" as const,
  errorCorrection: "M" as const,
  sizePixels: 512,
};

/**
 * End-to-end QR creation: generate QUC -> render image -> mask shape ->
 * persist to disk -> persist DB record. This is the single entry point
 * the /api/qr/generate route calls.
 */
export async function createQr(input: CreateQRInput): Promise<QRRecord> {
  const adapter = getAdapter();

  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;
  if (!baseUrl) {
    throw new ApiError(
      "CONFIG_ERROR",
      "NEXT_PUBLIC_BASE_URL is not configured on the server.",
      500,
    );
  }

  const uniqueCode = await generateUniqueCode(adapter);
  const trackingUrl = `${baseUrl.replace(/\/$/, "")}/verify/${uniqueCode}`;

  const dotShape = input.dotShape ?? DEFAULTS.dotShape;
  const eyeOuterShape = input.eyeOuterShape ?? DEFAULTS.eyeOuterShape;
  const eyeInnerShape = input.eyeInnerShape ?? DEFAULTS.eyeInnerShape;
  const fgColor = input.fgColor ?? DEFAULTS.fgColor;
  const bgColor = input.bgColor ?? DEFAULTS.bgColor;
  const overallShape = input.overallShape ?? DEFAULTS.overallShape;
  const sizePixels = input.sizePixels ?? DEFAULTS.sizePixels;
  // Per spec 3.1.7: default to H error correction whenever a logo is used.
  const errorCorrection =
    input.errorCorrection ?? (input.logoUrl ? "H" : DEFAULTS.errorCorrection);

  let logoBuffer: Buffer | undefined;
  if (input.logoUrl) {
    const res = await fetch(input.logoUrl);
    if (!res.ok) {
      throw new ApiError(
        "LOGO_FETCH_FAILED",
        "Could not fetch the provided logoUrl.",
        400,
      );
    }
    logoBuffer = Buffer.from(await res.arrayBuffer());
  }

  const { png, svg } = await renderQr({
    data: trackingUrl,
    sizePixels,
    dotShape,
    eyeOuterShape,
    eyeInnerShape,
    fgColor,
    bgColor,
    gradient: input.gradient,
    errorCorrection,
    overallShape,
    cornerRadius: input.cornerRadius,
    logoBuffer,
  });

  const imageStoragePath = await saveQrImage(png, `${uniqueCode}.png`);
  const svgStoragePath = await saveSvgFile(svg, `${uniqueCode}.svg`);

  const record = await adapter.createQR({
    uniqueCode,
    originalUrl: input.originalUrl,
    trackingUrl,
    label: input.label ?? null,
    dotShape,
    eyeOuterShape,
    eyeInnerShape,
    fgColor,
    bgColor,
    overallShape,
    cornerRadius: input.cornerRadius ?? null,
    errorCorrection,
    logoUrl: input.logoUrl ?? null,
    sizePixels,
    imageStoragePath,
    svgStoragePath,
    scanCount: 0,
    scanLogs: [],
    createdBy: input.createdBy ?? null,
    isActive: true,
  });

  return record;
}

export async function getQrByCode(uniqueCode: string): Promise<QRRecord> {
  const record = await getAdapter().getQRByCode(uniqueCode);
  if (!record) {
    throw new ApiError(
      "QR_NOT_FOUND",
      "No QR code found for the given unique code.",
      404,
    );
  }
  return record;
}

/**
 * Records a scan. Spec 3.3.1: only increments/logs when the QR is active;
 * deactivated codes get a distinct response and no counter movement.
 */
export async function recordScan(
  uniqueCode: string,
  clientInfo: Omit<ScanLogEntry, "scannedAt">,
): Promise<{ record: QRRecord; deactivated: boolean }> {
  const existing = await getAdapter().getQRByCode(uniqueCode);
  if (!existing) {
    throw new ApiError(
      "QR_NOT_FOUND",
      "This QR code was not generated by TalentYug systems or does not exist.",
      404,
    );
  }

  if (!existing.isActive) {
    return { record: existing, deactivated: true };
  }

  const updated = await getAdapter().incrementScan(uniqueCode, {
    ...clientInfo,
    scannedAt: new Date().toISOString(),
  });

  if (!updated) {
    throw new ApiError(
      "QR_NOT_FOUND",
      "No QR code found for the given unique code.",
      404,
    );
  }

  return { record: updated, deactivated: false };
}

export async function deactivateQr(uniqueCode: string): Promise<QRRecord> {
  const updated = await getAdapter().deactivateQR(uniqueCode);
  if (!updated) {
    throw new ApiError(
      "QR_NOT_FOUND",
      "No QR code found for the given unique code.",
      404,
    );
  }
  return updated;
}

export async function activateQr(uniqueCode: string): Promise<QRRecord> {
  const updated = await getAdapter().activateQR(uniqueCode);
  if (!updated) {
    throw new ApiError(
      "QR_NOT_FOUND",
      "No QR code found for the given unique code.",
      404,
    );
  }
  return updated;
}
