import { NextRequest, NextResponse } from 'next/server';
import { recordScan } from '@/services/qrService';
import { ApiError } from '@/lib/errors';

interface Params {
  params: { uniqueCode: string };
}

function wantsJson(req: NextRequest): boolean {
  return (req.headers.get('accept') ?? '').includes('application/json');
}

function getClientIp(req: NextRequest): string {
  // Standard proxy headers; falls back to 'unknown' in local dev where
  // there's no reverse proxy setting these.
  const forwarded = req.headers.get('x-forwarded-for');
  if (forwarded) return forwarded.split(',')[0].trim();
  return req.headers.get('x-real-ip') ?? 'unknown';
}

function htmlPage(title: string, bodyHtml: string, status: number) {
  return new NextResponse(
    `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${title}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; background:#f5f5f7; display:flex; align-items:center; justify-content:center; height:100vh; margin:0; }
    .card { background:#fff; padding:2.5rem; border-radius:12px; box-shadow:0 4px 24px rgba(0,0,0,0.08); max-width:420px; text-align:center; }
    h1 { font-size:1.25rem; margin-bottom:0.5rem; }
    p { color:#555; }
  </style>
</head>
<body>
  <div class="card">${bodyHtml}</div>
</body>
</html>`,
    { status, headers: { 'Content-Type': 'text/html; charset=utf-8' } }
  );
}

export async function GET(req: NextRequest, { params }: Params) {
  const { uniqueCode } = params;
  const wantJson = wantsJson(req);

  try {
    const { record, deactivated } = await recordScan(uniqueCode, {
      ipAddress: getClientIp(req),
      userAgent: req.headers.get('user-agent') ?? 'unknown',
    });

    if (deactivated) {
      // Spec 3.3.1 case 3: deactivated - do not reveal original URL,
      // do not increment scan count.
      if (wantJson) {
        return NextResponse.json(
          { status: 'deactivated', uniqueCode, message: 'This QR code has been deactivated.' },
          { status: 200 }
        );
      }
      return htmlPage(
        'QR Code Deactivated',
        `<h1>QR Code Deactivated</h1><p>This QR code has been deactivated by its owner and is no longer active.</p>`,
        200
      );
    }

    // Active scan recorded successfully - spec 3.3.1 case 2.
    if (wantJson) {
      return NextResponse.json(
        {
          status: 'verified',
          uniqueCode: record.uniqueCode,
          label: record.label,
          originalUrl: record.originalUrl,
          createdAt: record.createdAt,
          scanCount: record.scanCount,
          isActive: record.isActive,
        },
        { status: 200 }
      );
    }

    // Browser visit: show a short confirmation, then redirect to the
    // original URL after a brief configurable delay.
    const delaySeconds = Number(process.env.VERIFY_REDIRECT_DELAY_SECONDS ?? 2);
    return htmlPage(
      'QR Code Verified',
      `<h1>✅ QR Code Verified</h1>
       <p>${record.label ? escapeHtml(record.label) + ' — ' : ''}Redirecting you now...</p>
       <script>setTimeout(() => { window.location.href = ${JSON.stringify(record.originalUrl)}; }, ${delaySeconds * 1000});</script>`,
      200
    );
  } catch (err) {
    // Spec 3.3.1 case 4: not found.
    if (err instanceof ApiError && err.statusCode === 404) {
      if (wantJson) {
        return NextResponse.json(
          { error: true, code: err.code, message: err.message, statusCode: 404 },
          { status: 404 }
        );
      }
      return htmlPage(
        'QR Code Not Found',
        `<h1>❌ Not Found</h1><p>This QR code was not generated by TalentYug systems or does not exist.</p>`,
        404
      );
    }

    console.error('Verify route error:', err);
    if (wantJson) {
      return NextResponse.json(
        { error: true, code: 'INTERNAL_ERROR', message: 'Something went wrong.', statusCode: 500 },
        { status: 500 }
      );
    }
    return htmlPage('Error', `<h1>Something went wrong</h1><p>Please try again later.</p>`, 500);
  }
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
